### ISSUE TITLE
remake problem

### ISSUE THREAD

**Issue by lmguzman** [aammd/CoffeeCoop#9]
Andrew..., I think we have a problem, I dont think remake is available for the latest version of R :(

**Comment by lmguzman** [comment]
@aammd

**Comment by aammd** [comment]
it isn't on CRAN just yet, I don't believe. You'll need to reinstall it with `devtools::install_github("richfitz/remake")`
ping @richfitz just in case this is a bigger issue

**Comment by richfitz** [comment]
Nope, that's the error message that `install.packages("remake")` would give.  `storr` is also required, so `devtools::install_packages(c("richfitz/storr", "richfitz/remake"))` should work.

**Comment by richfitz** [comment]
Confusingly, that "Nope" above should be interpreted as "I agree with @aammd's diagnosis above", which is probably not normative use of the word.

**Comment by lmguzman** [comment]
Thanks!! I finally got it working :D
